



[Main]
library=1
directory=0
AutoLoad=0
Calc48=1
KeepAll=0
UseDefaultEntryList=1
LoadOnly=0
EMUVisible=1
ProjectTab=2
EntryPointList=
Title=NAV48 :Hpsaturn Navigator, Build PC v1.0 Beta
Config=
ExtPrg=
Message=
Romid=200
Slot=0
Emu48Ram=D:\devel\HP\work\main20050515.E48
Emu48Port2=D:\devel\HP\work\Slot2.bin
Emu49Ram=C:\Archivos de programa\Hewlett-Packard\Debug4x\Emu\default.e49
FilePath=Prueba.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[MsgText]
msgtext1=Sistema de Navegacion para Rally.
msgtext2=Version compilada en PC
msgtext3=Beta Testing 1.0
[Files]
file1=CkNoExp.s
file2=DoVTime.s
file3=MsgBox.s
file4=ViewTrm.s
file5=DrpBadKey.s
file6=BigGrob.s
file7=MakeFont.s
file8=SetText.s
file9=ToolsSTR.s
file10=ToolsTAG.s
file11=main.S
[Edit]
edit1=main.S
edit2=KEY.H
edit3=ViewTrm.s
edit4=Vars.h
edit5=Def.h
edit6=EnterKey.h
