RPL 
( C:\Archivos de programa\Hewlett-Packard\Debug4x\Examples\Rally\GUI.h, part of the saturn.HPP project, created by <Hpsaturn> on 15/05/2005 )

( GUI )
*********************************
*DECORACION E INTERFAZ		*
*********************************

( Lineas horizontales principales )
0  18 131 18 LINEON
0  55 131 55 LINEON
( Division Hora )
76 28 131 28 LINEON
( Division Vertical Tiempos )
76 19 76  54 LINEON

"XR:"	 1  20	IFNT2
"XI:"	 1  28	IFNT2
"Spd:"	 84 0	IFNT1
"KI:"	 84 6	IFNT1
"Trm:"	 84 12	IFNT1
"Start:" 1  49	IFNT1
"TimeT:" 1  43	IFNT1
"DistT:" 1  37	IFNT1

"ADD" "VIEW" "ODO2" "çHMS" "èê"
"EXIT"
6 {}N

InitMenu
DispMenu.1

